#############################################################################################


| File Header  |  |
| --------- | -----------      |
| Title     | PyTorch          |
| Author    | balarcode        |
| Version   | 1.1              |
| Date      | 11th August 2025 |
| File Type | Jupyter Notebook |
| File Test | Verified on Jupyter Notebook 7.4.4 |
| Comments  | Algorithms, concepts and techniques using PyTorch machine learning framework.|
|All Rights Reserved.|


#############################################################################################

Install packages and libraries using the following command:

pip3 install torch torchvision

In [1]:
# Import Packages and Libraries
import torch # Import PyTorch

In [2]:
# Create Tensors

# Create a tensor with all zeros
tensor_a = torch.zeros(5, 3)
print("Create a tensor with all zeros and of default 32-bit floating data type: ")
print(tensor_a) # Print the tensor contents
print(tensor_a.dtype) # Print the data type of the tensor
print("\n")

# Create a tensor with all ones and of 32-bit integer data type
tensor_b = torch.ones((5, 3), dtype=torch.int32)
print("Create a tensor with all ones and of 32-bit integer data type: ")
print(tensor_b)
print(tensor_b.dtype)
print("\n")

# Create a tensor as a matrix with random values drawn from standard normal distribution
torch.manual_seed(0)
tensor_c = torch.rand(5, 3)
print("Create a tensor as a matrix with random values drawn from standard normal distribution: ")
print(tensor_c)
print(tensor_c.dtype)
print("\n")

# Create a tensor as a vector with random values drawn from standard normal distribution
torch.manual_seed(0)
tensor_d = torch.rand(1, 10)
print("Create a tensor as a vector with random values drawn from standard normal distribution: ")
print(tensor_d)
print(tensor_d.dtype)
print("\n")

# Create an image tensor of image size = 8x8 with 1 color channel and with 4 images in 1 batch
tensor_image = torch.rand(4, 1, 8, 8) # Returned tensor is filled with random values in the interval [0,1)
print("Create an image tensor of image size = 8x8 with 1 color channel and with 4 images in 1 batch: ")
print(tensor_image)
print(tensor_image.shape)
print(tensor_image.dtype)


Create a tensor with all zeros and of default 32-bit floating data type: 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


Create a tensor with all ones and of 32-bit integer data type: 
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.int32


Create a tensor as a matrix with random values drawn from standard normal distribution: 
tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939]])
torch.float32


Create a tensor as a vector with random values drawn from standard normal distribution: 
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964, 0.4556,
         0.6323]])
torch.float32


Create an image tensor of image size = 8x8 with 1 color channel and with 4 images in 1 batch: 
tensor([[[[0.3489, 0.4017, 0.0

In [3]:
# Mathematical Operations on Tensors
torch.manual_seed(0)
A = torch.rand(2, 2)
print("Matrix 'A' with random values: ")
print(A)
print("\n")

B = torch.rand(2, 2)
print("Matrix 'B' with random values: ")
print(B)
print("\n")

# Normalize the tensor in the range [0, 1]
A -= A.data.min()
A /= A.data.max()
print("Normalize the tensor 'A' in the range [0, 1]: ")
print(A)
print("\n")

print("Absolute value of matrix 'A': ")
print(torch.abs(A))
print("\n")

print("Determinant of matrix 'A': ")
print(torch.det(A))
print("\n")

print("Singular Value Decomposition (SVD) of matrix 'A': ")
print(torch.svd(A))
print("\n")

print("Maximum value of matrix 'A': ")
print(torch.max(A))
print("\n")

print("Minimum value of matrix 'A': ")
print(torch.min(A))
print("\n")

print("Mean and Standard Deviation of matrix 'A': ")
print(torch.std_mean(A))
print("\n")

print("Matrix multiplication between matrices 'A' and 'B': ")
print(torch.mm(A, B))
print("\n")

Matrix 'A' with random values: 
tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])


Matrix 'B' with random values: 
tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])


Normalize the tensor 'A' in the range [0, 1]: 
tensor([[0.5999, 1.0000],
        [0.0000, 0.0641]])


Absolute value of matrix 'A': 
tensor([[0.5999, 1.0000],
        [0.0000, 0.0641]])


Determinant of matrix 'A': 
tensor(0.0384)


Singular Value Decomposition (SVD) of matrix 'A': 
torch.return_types.svd(
U=tensor([[ 0.9989, -0.0471],
        [ 0.0471,  0.9989]]),
S=tensor([1.1674, 0.0329]),
V=tensor([[ 0.5133, -0.8582],
        [ 0.8582,  0.5133]]))


Maximum value of matrix 'A': 
tensor(1.)


Minimum value of matrix 'A': 
tensor(0.)


Mean and Standard Deviation of matrix 'A': 
(tensor(0.4732), tensor(0.4160))


Matrix multiplication between matrices 'A' and 'B': 
tensor([[0.6745, 1.2768],
        [0.0314, 0.0574]])


