#############################################################################################

|           |                  |
| --------- | -----------      |
| Title     | PyTorch          |
| Author    | balarcode        |
| Version   | 1.6              |
| Date      | 18th September 2025 |
| File Type | Jupyter Notebook |
| File Test | Verified on Jupyter Notebook 7.4.4 |
| Comments  | Algorithms, concepts and techniques using PyTorch machine learning framework.|
|All Rights Reserved.|         |

#############################################################################################

Install packages and libraries using the following command:

```
pip3 install torch torchvision
```

In [1]:
# Import Packages and Libraries
import torch # Import PyTorch
import matplotlib.pyplot as plt

In [2]:
# Create Tensors

# Create a tensor with all zeros
tensor_a = torch.zeros(5, 3)
print("Create a tensor with all zeros and of default 32-bit floating data type: ")
print(tensor_a) # Print the tensor contents
print(tensor_a.shape) # Print the shape of the tensor
print(tensor_a.dtype) # Print the data type of the tensor
print("\n")

# Create a tensor with all ones and of 32-bit integer data type
tensor_b = torch.ones((5, 3), dtype=torch.int32)
print("Create a tensor with all ones and of 32-bit integer data type: ")
print(tensor_b) # Print the tensor contents
print(tensor_b.shape) # Print the shape of the tensor
print(tensor_b.dtype) # Print the data type of the tensor
print("\n")

# Create a tensor as a matrix with random values drawn from standard normal distribution
torch.manual_seed(0)
tensor_c = torch.rand(5, 3)
print("Create a tensor as a matrix with random values drawn from standard normal distribution: ")
print(tensor_c)
print(tensor_c.dtype)
print("\n")

# Create a tensor as a vector with random values drawn from standard normal distribution
torch.manual_seed(0)
tensor_d = torch.rand(1, 10)
print("Create a tensor as a vector with random values drawn from standard normal distribution: ")
print(tensor_d)
print(tensor_d.dtype)
print("\n")

# Create an image tensor of image size = 8x8 with 1 color channel and with 4 images in 1 batch
tensor_image = torch.rand(4, 1, 8, 8) # Returned tensor is filled with random values in the interval [0,1)
print("Create an image tensor of image size = 8x8 with 1 color channel and with 4 images in 1 batch: ")
print(tensor_image)
print(tensor_image.shape)
print(tensor_image.dtype)
print("\n")

# Create an empty tensor of size = 4x4 and of 64-bit integer data type
tensor_e = torch.empty((4, 4), dtype=torch.long)
print("Create an empty tensor of size = 4x4 and of 64-bit integer data type: ")
print(tensor_e) # Print the tensor contents
print(tensor_e.shape) # Print the shape of the tensor
print(tensor_e.dtype) # Print the data type of the tensor
print("\n")

# Create a tensor using torch.arange similar to Python's built-in range() function
tensor_f = torch.arange(start=0, end=10, step=2)
print("Create a tensor using torch.arange similar to Python's built-in range() function: ")
print(tensor_f) # Print the tensor contents
print(tensor_f.shape) # Print the shape of the tensor
print(tensor_f.dtype) # Print the data type of the tensor
print("\n")

# Create a tensor for identity matrix
tensor_g = torch.eye(5, 5)
print("Create a tensor for identity matrix: ")
print(tensor_g) # Print the tensor contents
print(tensor_g.shape) # Print the shape of the tensor
print(tensor_g.dtype) # Print the data type of the tensor
print("\n")

# Create a tensor with all ones, with requires_grad=True and of 64-bit floating data type
tensor_h = torch.ones((5, 3), dtype=torch.double, requires_grad=True)
print("Create a tensor with all ones, with requires_grad=True and of 64-bit floating data type: ")
print(tensor_h) # Print the tensor contents
print(tensor_h.shape) # Print the shape of the tensor
print(tensor_h.dtype) # Print the data type of the tensor
print("\n")


Create a tensor with all zeros and of default 32-bit floating data type: 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([5, 3])
torch.float32


Create a tensor with all ones and of 32-bit integer data type: 
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.Size([5, 3])
torch.int32


Create a tensor as a matrix with random values drawn from standard normal distribution: 
tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939]])
torch.float32


Create a tensor as a vector with random values drawn from standard normal distribution: 
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964, 0.4556,
         0.6323]])
torch.float32


Create an image tensor of image size = 8x8 with 1 color channel and with 4 images in 1 

In [3]:
# Mathematical Operations on Tensors

torch.manual_seed(0)
A = torch.rand(2, 2)
print("Matrix 'A' with random values: ")
print(A)
print("\n")

B = torch.rand(2, 2)
print("Matrix 'B' with random values: ")
print(B)
print("\n")

# Normalize the tensor in the range [0, 1]
A -= A.data.min()
A /= A.data.max()
print("Normalize the tensor 'A' in the range [0, 1]: ")
print(A)
print("\n")

print("Absolute value of matrix 'A': ")
print(torch.abs(A))
print("\n")

print("Determinant of matrix 'A': ")
print(torch.det(A))
print("\n")

print("Singular Value Decomposition (SVD) of matrix 'A': ")
print(torch.svd(A))
print("\n")

print("Maximum value of matrix 'A': ")
print(torch.max(A))
print("\n")

print("Minimum value of matrix 'A': ")
print(torch.min(A))
print("\n")

print("Mean and Standard Deviation of matrix 'A': ")
print(torch.std_mean(A))
print("\n")

print("Matrix multiplication between matrices 'A' and 'B': ")
print(torch.mm(A, B))
print("\n")

Matrix 'A' with random values: 
tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])


Matrix 'B' with random values: 
tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])


Normalize the tensor 'A' in the range [0, 1]: 
tensor([[0.5999, 1.0000],
        [0.0000, 0.0641]])


Absolute value of matrix 'A': 
tensor([[0.5999, 1.0000],
        [0.0000, 0.0641]])


Determinant of matrix 'A': 
tensor(0.0384)


Singular Value Decomposition (SVD) of matrix 'A': 
torch.return_types.svd(
U=tensor([[ 0.9989, -0.0471],
        [ 0.0471,  0.9989]]),
S=tensor([1.1674, 0.0329]),
V=tensor([[ 0.5133, -0.8582],
        [ 0.8582,  0.5133]]))


Maximum value of matrix 'A': 
tensor(1.)


Minimum value of matrix 'A': 
tensor(0.)


Mean and Standard Deviation of matrix 'A': 
(tensor(0.4732), tensor(0.4160))


Matrix multiplication between matrices 'A' and 'B': 
tensor([[0.6745, 1.2768],
        [0.0314, 0.0574]])




In [4]:
# Tensor Dimensions

print("Zero-dimensional tensor (scalar): ")
scalar_0d = torch.tensor(1.0)
print(scalar_0d.shape)
print("Number of dimensions: {}".format(scalar_0d.ndim))
print(scalar_0d)
print("\n")

print("One-dimensional tensor (vector): ")
vector_1d = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
print(vector_1d.shape)
print("Number of dimensions: {}".format(vector_1d.ndim))
print(vector_1d)
print("\n")

print("One-dimensional tensor (vector): ")
torch.manual_seed(0)
vector_random_1d = torch.rand(4)
print(vector_random_1d.shape)
print("Number of dimensions: {}".format(vector_random_1d.ndim))
print(vector_random_1d)
print("\n")

print("Two-dimensional tensor (matrix): ")
matrix_2d_a = torch.tensor([[1, 2, 3, 4],
                            [5, 6, 7, 8]])
print(matrix_2d_a.shape)
print("Number of dimensions: {}".format(matrix_2d_a.ndim))
print(matrix_2d_a)
print("\n")

print("Two-dimensional tensor (matrix): ")
matrix_2d_b = torch.tensor([[1, 2, 3, 4, 5, 6, 7, 8]])
print(matrix_2d_b.shape)
print("Number of dimensions: {}".format(matrix_2d_b.ndim))
print(matrix_2d_b)
print("\n")

print("Three-dimensional tensor: ")
tensor_3d = torch.ones(2, 3, 2)
print(tensor_3d.shape)
print("Number of dimensions: {}".format(tensor_3d.ndim))
print(tensor_3d)
print("\n")

print("Three-dimensional tensor for a grayscale image: ")
IMG_SIZE = 224
image = torch.randn(1, IMG_SIZE, IMG_SIZE)
print(image.shape)
print("Number of dimensions: {}".format(image.ndim))
print("\n")

print("Four-dimensional tensor for a grayscale image: ")
image = image.unsqueeze(0) # Add fourth dimension (batch-size) by unsqueezing along axis-0
print(image.shape)
print("Number of dimensions: {}".format(image.ndim))


Zero-dimensional tensor (scalar): 
torch.Size([])
Number of dimensions: 0
tensor(1.)


One-dimensional tensor (vector): 
torch.Size([8])
Number of dimensions: 1
tensor([1, 2, 3, 4, 5, 6, 7, 8])


One-dimensional tensor (vector): 
torch.Size([4])
Number of dimensions: 1
tensor([0.4963, 0.7682, 0.0885, 0.1320])


Two-dimensional tensor (matrix): 
torch.Size([2, 4])
Number of dimensions: 2
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


Two-dimensional tensor (matrix): 
torch.Size([1, 8])
Number of dimensions: 2
tensor([[1, 2, 3, 4, 5, 6, 7, 8]])


Three-dimensional tensor: 
torch.Size([2, 3, 2])
Number of dimensions: 3
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])


Three-dimensional tensor for a grayscale image: 
torch.Size([1, 224, 224])
Number of dimensions: 3


Four-dimensional tensor for a grayscale image: 
torch.Size([1, 1, 224, 224])
Number of dimensions: 4


In [5]:
# Check For Device Availability

if torch.cpu.is_available():
    print("CPU Available - For General Purpose Computing")
    device = torch.device("cpu")
else:
    print("CPU Not Available")

if torch.cuda.is_available():
    print("CUDA-Enabled GPU Available - For Acceleration On NVIDIA GPUs")
    device = torch.device("cuda")
else:
    print("CUDA-Enabled GPU Not Available")

if torch.backends.mps.is_available():
    print("MPS-Enabled Device Available - For Acceleration On Apple Silicon Macs")
    device = torch.device("mps")
else:
    print("MPS-Enabled Device Not Available")

if torch.xpu.is_available():
    print("XPU Available - For Acceleration On Intel GPUs")
    device = torch.device("xpu")
else:
    print("XPU Not Available")

CPU Available - For General Purpose Computing
CUDA-Enabled GPU Not Available
MPS-Enabled Device Available - For Acceleration On Apple Silicon Macs
XPU Not Available


In [6]:
# Tensor Indexing

tensor_x = torch.arange(start=10, end=35, step=1)
tensor_y = torch.arange(25).reshape(5, 5)
print(f"1D tensor (vector): \n {tensor_x = }, {tensor_x.shape = }, {tensor_x.ndim = }")
print(f"2D tensor (matrix): \n {tensor_y = }, {tensor_y.shape = }, {tensor_y.ndim = }")
print("\n")

print("Fetch alternating elements from the 1D tensor (vector): ")
print(tensor_x[::2])
print("\n")

print("Fetch first 10 elements from the 1D tensor (vector): ")
print(tensor_x[0:10])
print("\n")

print("Fetch last 10 elements from the 1D tensor (vector): ")
print(tensor_x[-10:])
print("\n")

print("Fetch odd-valued elements from the 1D tensor (vector): ")
tensor_x1 = torch.where(tensor_x % 2 != 0, tensor_x, 0) # Return a tensor with even values zeroed out and containing only odd values
indices = torch.nonzero(tensor_x1, as_tuple=True) # Find the indices to the non-zero values i.e. the odd values
print(tensor_x1[indices])
print("\n")

print("Fetch the second column vector from the 2D tensor (matrix): ")
print(tensor_y[:, 1])
print("\n")

print("Fetch the last row vector from the 2D tensor (matrix): ")
print(tensor_y[-1, :])
print("\n")

print("Fetch the main diagonal of the 2D tensor (matrix): ")
print(torch.diagonal(tensor_y, offset=0))
print("\n")

print("Fetch the off diagonal of the 2D tensor (matrix): ")
print(torch.diagonal(torch.fliplr(tensor_y)))
print("\n")

print("Fetch the first three elements of third row vector from the 2D tensor (matrix): ")
print(tensor_y[2, 0:3])
print("\n")

print("Fetch the 13th element from the 2D tensor (matrix): ")
print(torch.flatten(tensor_y)[12])
print("\n")


1D tensor (vector): 
 tensor_x = tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34]), tensor_x.shape = torch.Size([25]), tensor_x.ndim = 1
2D tensor (matrix): 
 tensor_y = tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]), tensor_y.shape = torch.Size([5, 5]), tensor_y.ndim = 2


Fetch alternating elements from the 1D tensor (vector): 
tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34])


Fetch first 10 elements from the 1D tensor (vector): 
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])


Fetch last 10 elements from the 1D tensor (vector): 
tensor([25, 26, 27, 28, 29, 30, 31, 32, 33, 34])


Fetch odd-valued elements from the 1D tensor (vector): 
tensor([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])


Fetch the second column vector from the 2D tensor (matrix): 
tensor([ 1,  6, 11, 16, 21])


Fetch the last row